### ISSUE TITLE
Both-Way Links Descriptions?

### ISSUE THREAD

**Issue by nclm** [CyberCRI/KnowNodes#114]
Is a way to describe a link both ways needed? [Georges Perec] “wrote” [Life: A User's Manuall] and [Life: A User's Manual] “is written by” [Georges Perec].

**Comment by Garbash** [comment]
I figured that it's not that important because a two way link is pretty
self describing from a user's point of view.
It's true that if we need a large scale reasoning system, it would be good
to have that, but until then, we should try to make life as easy as
possible for our users.

On Thu, Nov 7, 2013 at 8:33 AM, nicolas notifications@github.com wrote:

> Is a way to describe a link both ways needed? [Georges Perec] “wrote”
> [Life: A User's Manuall] and [Life: A User's Manual] “is written by”
> [Georges Perec].
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CyberCRI/KnowNodes/issues/114
> .

## 

Get some insight of what makes me tick:
My twitter https://twitter.com/#!/garbash
Knownodes mailing list https://groups.google.com/forum/#!forum/knownodes

Dor Garbash
108 Rue du faubourg du temple, Paris 75011
+33-652919878
