### ISSUE TITLE
Link relevance query fails in some cases

### ISSUE THREAD

**Issue by drpepper** [CyberCRI/KnowNodes#24]
Some links lack the "relevance" attribute, as can be seen by this query:

```
start root=node(*)
where has(root.connectionType) and not has(root.relevance)
return root
```

This might be because the query to calculate relevance assumes that one common friend (in the database, not on Wikipedia itself). If no so friends exist, perhaps the query fails?

**Comment by brumar** [comment]
yes, it must be this cause. Moreover, even if we avoid this error, it would be zero at the end, which is not meaningfull. I would suggest to consider the existing direct link as a virtual common friend. Then the link relevance will be at least 1/N where N is the number of links from the starting node (the actual formula would be (x+1)/N with x the number of common friend. It does not endanger the drunken walk analogy because no need to access a node in two step if you have reached the ending node in 1 step :).

**Comment by drpepper** [comment]
Perhaps we could use this optional relationship syntax, then :

http://docs.neo4j.org/chunked/milestone/query-match.html#match-optional-relationship

2013/6/19 brumar notifications@github.com
