### ISSUE TITLE
Notification module

### ISSUE THREAD

**Issue by Garbash** [CyberCRI/KnowNodes#79]
![photo on 10-11-13 at 5 18 pm](https://f.cloud.github.com/assets/1841864/1315583/aad570f6-3288-11e3-9e23-9f10041f1887.jpg)

Objectives:
1. Engage users by giving them rapid feedback for their actions in the system
2.    Facilitate collaboration

User receives notifications in two ways:

1) Via topbar on website
2) Via email notifications

////Topbar in website:
- A box with a red icon showing number of notifications:
- A click on the box opens  a list of sentences in this format: 
  [user who did the action][action][target of the action]
- Events that trigger a new Notification:
- new comment on a user's connection
- new comment on a connection commented by user
- new connection to a resource connected by user
- vote up/down on connection created by user
- When vote notification is updated  program adds up new votes on same target( if two upvotes received, user get notified only once, that 2 votes has been received)
- the notification lists up to 100 latest notifications
- On opening notification box, first seen notifications have different a background.

///Email notifications:
- A daily email summarising notifications is sent
- Styling wise, we should aim for minimal amount of links one links in email -
  http://ilyabirman.net/meanwhile/all/one-link/
- "Though there are some variations between people, according to their research, the best possible times to send emails for open rates and click through is between 8:00 A.M. and 10:00 A.M or between 3:00 P.M. and 4:00 P.M."
  http://www.businessinsider.com/best-time-to-send-email-2012-11#ixzz2hQOTdgOQ
- Votes don't appear in the daily digest.
- Unsubscribe/Subscribe button is provided

///Relevant material:

Notifications on angular js:
http://codingsmackdown.tv/blog/2013/04/29/hailing-all-frequencies-communicating-in-angularjs-with-the-pubsub-design-pattern/

**Comment by deemeetree** [comment]
Hi Dor,

Very good idea. Something like this is implemented in http://thisislike.com where users are automatically subscribed to the items they add. 
Clicking the "subscribe" button also makes it possible to subscribe to the resources that they connect to. 
I think that subscribing them by default to all the items they ever connect is a good rule, because they will be interested to see when the new connection is made.
The subscribe/unsubscribe button could make it easy to switch off individual notifications.

The notification box - basically it's a live news feed, so maybe there's a point of also adding a dedicated page with all the notifications listed? This could later be transformed into some kind of login start page where you can see what's going on with the resources you're interested with. When later people start adding each other as "friends" (if that ever happens), notifications could easily be expanded when users add new friends or create new items.

**Comment by Garbash** [comment]
I agree with both points:
- Follow/unfollow button for nodes - should be some sort of button that reveals on hover
  ![screen shot 2013-10-14 at 11 44 50 am](https://f.cloud.github.com/assets/1841864/1324600/a6dbf8c4-34b5-11e3-81d9-acca2530ed99.png)
- Putting on the front page a notification stream might be interesting - and it won't be a lot of work.
  We should dedicate some time to think how to best implement it.

**Comment by Garbash** [comment]
Json requirements from the client for a notification:

action: "create"/"comment"/"follow"/"vote"
actor: 
       userName:
       id:
target: Resource/Connection
creationDate: Date
alreadyRead: boolean
